'''
IIIIIIIII   IIIIIIIII   IIIIIIIII   IIIIIIIII   III   IIIIIIIII 
IIIIIIIII   IIIIIIIII   IIIIIIIII   IIIIIIIII   III   IIIIIIIII
   III      III            III      III   III   III   III
   III      III            III      III   III   III   III
   HHH      HHHHHH         HHH      HHHHHH      III   HHHHHHHHH
   HHH      HHHHHH         HHH      HHHHHH      III   HHHHHHHHH
   HHH      HHH            HHH      HHH   HHH   III         HHH
   HHH      HHH            HHH      HHH   HHH   III         HHH
   HHH      HHHHHHHHH      HHH      HHH   HHH   III   HHHHHHHHH
   HHH      HHHHHHHHH      HHH      HHH   HHH   III   HHHHHHHHH
'''





IIIIIIIII
IIIIIIIII
III
III
HHHHHHHHH
HHHHHHHHH
      HHH
      HHH
HHHHHHHHH
HHHHHHHHH



III
III
III
III
HHH
HHH
HHH
HHH
HHH
HHH

IIIIIIIII
IIIIIIIII
III   III
III   III
HHHHHH
HHHHHH
HHH   HHH
HHH   HHH
HHH   HHH
HHH   HHH

